### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte in position X

### ISSUE THREAD

**Issue by ghost** [fengju514/Expression-Net#18]
I am receiving constantly an annoying error when I am trying to run the approach. More specifically, 

> net_data = np.load("fpn_new_model/PAM_frontal_ALexNet.npy").item()
> (Pdb) c
> Traceback (most recent call last):
>   File "/opt/libraries/anaconda3/envs//lib/python3.6/site-packages/numpy/lib/format.py", line 650, in read_array
>     array = pickle.load(fp, **pickle_kwargs)
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 0: ordinal not in range(128)

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main_ExpShapePoseNet.py", line 292, in <module>
>     tf.app.run()
>   File "/opt/libraries/anaconda3/envs//lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "main_ExpShapePoseNet.py", line 288, in main
>     extract_PSE_feats()
>   File "main_ExpShapePoseNet.py", line 100, in extract_PSE_feats
>     net_data = np.load("fpn_new_model/PAM_frontal_ALexNet.npy").item()
>   File "/opt/libraries/anaconda3/envs//lib/python3.6/site-packages/numpy/lib/npyio.py", line 421, in load
>     pickle_kwargs=pickle_kwargs)
>   File "/opt/libraries/anaconda3/envs//lib/python3.6/site-packages/numpy/lib/format.py", line 656, in read_array
>     "to numpy.load" % (err,))
> 

I am not sure what is happening but it seems that i has to do with loading the AlexNet file. What is strange is that 2 days before i run the code without issue with the same files. What can be wrong here?

**Comment by zhaishengfu** [comment]
the same error. do you have any answer for this problem?

**Comment by piyushapple1998** [comment]
Please provide a solution to this error
